article/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = "article"

urlpatterns = [
    path('dashboard/',views.dashboard,name="dashboard"),
    path('addarticle/',views.addArticle,name="addarticle"),
    path('detail/<int:id>',views.details,name="detail"),
    path('update/<int:id>',views.updateArticle,name="update"),
    path('delete/<int:id>',views.deleteArticle,name="delete"),
    path('comment/<int:id>',views.addComment,name="comment"),
    path('',views.showArticles,name="show"),
    
]

blog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

from article import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"), #* Django da root dizine gitmek icin bos birakmak gerekiyor.
    path('about/', views.about,name="about"),
    path('articles/', include("article.urls"), name="article"),
    path('user/', include("user.urls"), name="user"),
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

article/models.py
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field
# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE) #* Burada auth.User daki User silinirse article daki butun verielr de silenecek
    title =  models.CharField(max_length=50)
    content = CKEditor5Field('Content',config_name='extends',blank=True)
    created_date = models.DateTimeField(auto_now_add=True) #* Eklendigi tarihi otomatik olarak almasini saglayan parametre
    updated_date = models.DateTimeField(auto_now = True)
    article_img = models.FileField(blank=True,null=True,verbose_name="Add Image to your Article.")

    def __str__(self):
        return self.title
    class Meta:
        ordering = ['-created_date']

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete = models.CASCADE,verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50,verbose_name = "name")
    comment_station = models.CharField(max_length=2,verbose_name="station")
    comment_content = models.CharField(max_length = 200,verbose_name = "Content")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_author
    class Meta:
        ordering = ['-comment_date']

article/forms.py
from django import forms
from .models import Article
from django_ckeditor_5.widgets import CKEditor5Widget

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title","content","article_img"]
        

article/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse

from .models import Article,Comment
from .forms import ArticleForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from textblob import TextBlob
# Create your views here.


def index(request):
    
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")


@login_required(login_url= "user:login")
def dashboard(request):
    article = Article.objects.filter(author = request.user)
    context = {
        "articles":article
    }
    return render(request,"dashboard.html",context)

def details(request,id):
    #article = Article.objects.filter(id=id).first()
    article = get_object_or_404(Article,id = id)
    months = {1:"January",
                  2:"Fabruary",
                  3:"March",
                  4:"April",
                  5:"May",
                  6:"June",
                  7:"July",
                  8:"August",
                  9:"September",
                  10:"October",
                  11:"November",
                  12:"December",}
    month_name = months[article.created_date.month]
    comment = article.comments.all()
   
    context = {
        "article":article,
        "months":month_name,
        "comment":comment
    }

    return render(request,"detail.html",context)

@login_required(login_url= "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None,request.FILES or None)
    print(request.FILES)

    if form.is_valid():
        article = form.save(commit=False) #* Formumuzu Models.py dosyasindan olusturdugumuzdan sadece save() fonksiyonu ile save edebiliyoruz fakat save fonksiyonu bir article objesi create ediyor ve bunu commit etmeye calisiyor fakat biz bir author_id atamadik bu sebepten hata vermemesi icin commit false ile objeyi olusturuyoruz fakat commit ettirmiyoruz db'ye.
        article.author = request.user
        article.save()
        messages.success(request,"Article is successfully added.")
        return redirect("article:dashboard")

    return render(request,"addarticle.html",{"form":form})

@login_required(login_url= "user:login")
def updateArticle(request,id):
    article = get_object_or_404(Article,id=id)
    form = ArticleForm(request.POST or None,request.FILES or None,instance= article)
    if form.is_valid():
        article = form.save(commit=False) #* Formumuzu Models.py dosyasindan olusturdugumuzdan sadece save() fonksiyonu ile save edebiliyoruz fakat save fonksiyonu bir article objesi create ediyor ve bunu commit etmeye calisiyor fakat biz bir author_id atamadik bu sebepten hata vermemesi icin commit false ile objeyi olusturuyoruz fakat commit ettirmiyoruz db'ye.
        article.author = request.user
        article.save()
        messages.success(request,"Article is successfully updated.")
        return redirect("article:dashboard")

    context = {
        "form":form
    }
    return render(request,"update.html",context)

@login_required(login_url= "user:login")
def deleteArticle(request,id):
    article = get_object_or_404(Article,id = id)
    article.delete()
    messages.success(request,"Your Article Was Successfully Deleted.")
    
    return redirect("article:dashboard")

def showArticles(request):
    keyword = request.GET.get("keyword")

    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles":articles})

    articles = Article.objects.all()

    context = {
        "articles":articles
    }
    return render(request,"articles.html",context)

def addComment(request,id):
    article = get_object_or_404(Article,id = id)

    if request.method == "POST":
        comment_author = request.user.username
        comment_content = request.POST.get("comment_content")
        blob = TextBlob(comment_content)
        sentiment_score = blob.sentiment.polarity
        temp_sent = ''
        print(sentiment_score)
        if sentiment_score > 0:
            temp_sent = '1'
        elif sentiment_score < 0:
            temp_sent = '-1'
        else:
            temp_sent = '0'
        
        if comment_author != "" and comment_content != "":
            newComment = Comment(comment_author= comment_author,comment_content=comment_content,comment_station=temp_sent)
            newComment.article = article
            
            newComment.save()
            messages.success(request,"Yorum yaptiginiz icin tesekkurler")
            
        elif comment_author != "" and comment_content == "":
            messages.warning(request,"Bos bir Comment olusturamazsiniz.")
    
        elif comment_author == "" and comment_content != "":
            comment_author = "Anonymous"
            newComment = Comment(comment_author= comment_author,comment_content=comment_content,comment_station=temp_sent)
            newComment.article = article
            newComment.save()
            messages.success(request,"Yorum yaptiginiz icin tesekkurler")
        elif comment_author == "" and comment_content == "":
            messages.warning(request,"Bos bir Comment olusturamazsiniz.")
            
    return redirect(reverse("article:detail",kwargs={"id":id}))

templates/about.html
{% extends "layout.html" %}

{% block body %}
        <!-- Header - set the background image for the header in the line below-->
        <header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
            <div class="text-center my-5">
                <img class="img-fluid rounded-circle mb-4" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWOIGWNyrPWvRHu0hJ3xHjtTxpD4iuXxOjgpm6OfCwqA&s" alt="..." />
                <h1 class="text-white fs-3 fw-bolder">Sabri Alperen KAYA</h1>
                <p class="text-white-50 mb-0">CBÜ Computer Eng. (Grade 3)</p>
            </div>
        </header>
        <!-- Content section-->
        <section class="py-5">
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-lg-6">
                        <h2>Sabri Alperen KAYA (SAK) Blog</h2>
                        <p class="lead">Bu benim ilk Django framework'u ile gelistirmis oldugum web sitesi projem.</p>
                        <p class="mb-0">The universe is almost 14 billion years old, and, wow! Life had no problem starting here on Earth! I think it would be inexcusably egocentric of us to suggest that we're alone in the universe.</p>
                    </div>
                </div>
            </div>
        </section>


{% endblock body %}

templates/addarticle.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col">
        <h3>Add Article</h3>
        <hr>
    <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form | crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Add Article</button>
        </form>
        
    </div>
</div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

<h1>Articles</h1>
<hr>
<form action="/articles/" method="get" style="float:right"> 
        <div class="input-group mb-3">
            <input type="text" aria-label="Sizing example input" aria-describedby="inputGroup-sizing-default" placeholder="Search" name = "keyword">
            <button type="submit" class="btn btn-danger">Search</button>
        </div>
</form>

{% if articles %}

{% for article in articles %}

<div class="row">
    <div class="col-6 col-md-10 d-flex justify-content-center">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <a class="baslik" href="{% url 'article:detail' article.id%}"><h3 class="fw-bolder mb-1 baslik">{{article.title}}</h3> </a>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{months}} {{article.created_date.day}}, {{article.created_date.year}} by {{ article.author.username }} ,</div>

                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_img %}
                            <figure class="mb-4"><img style="width:450px;height:200px" class="img-fluid rounded" src="{{article.article_img.url}}" alt="..." /></figure>
                        {% else %}
                            <figure class="mb-4"><img style="width:450px;height:200px" class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">
                                <div class = "post_body">
                                    {{ article.content |safe|truncatewords:"30"|linebreaks }}
                                    <a style="float:right;" class="btn btn-outline-danger" href="{% url 'article:detail' article.id%}">READ MORE</a>
                                </div>
                            </p>
                        </section>
                    </article>
                    <br>
                    <hr>
                    
                </div>
    </div>
</div>

{% endfor %}



{% else %}

<div class="alert alert-danger">There Are No Articles.</div>

{% endif %}

{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

<h3>Control Dashboard</h3>
<hr>

<p>
You are welcome, <small> {{request.user.username}}</small>
</p>
<hr>

<a class="btn btn-danger" href="{% url 'article:addarticle'%}">Add Article</a>
<hr>

{% if articles %}
<div class="table-responsive">
<table class="table table-striped table-responsive-md">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Title</th>
      <th scope="col">Author</th>
      <th scope="col">Date</th>
      <th scope="col">Last Update Date</th>
      <th scope="col">Update</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    
    {% for article in articles %}
        <tr>
            <th scope="row">{{article.id}}</th>
            <td><a class="baslik" href="{% url 'article:detail' article.id%}">{{article.title}}</a></td>
            <td>{{article.author.username}}</td>
            <td>{{article.created_date| date:"d/m/Y H:i:s"}}</td>
            <td>{{article.updated_date | date:"d/m/Y H:i:s"}}</td>
            <td><a href="{% url 'article:update' article.id%}" class="btn btn-danger">Update</a></td>
            <td><a href="{% url 'article:delete' article.id%}" class="btn btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
  </tbody>
</table>
</div>
{% else %}

<div class="alert alert-danger"> You don't have any article yet.</div>
{% endif %}




{% endblock body %}

templates/detail.html
{% extends "layout.html" %}
{%load static%}

{% block body %}
<div class="row">
                <div class="col-lg-8">
                    <!-- Post content-->
                    <article>
                        <!-- Post header-->
                        <header class="mb-4">
                            <!-- Post title-->
                            <h1 class="fw-bolder mb-1">{{article.title}}</h1>
                            <!-- Post meta content-->
                            <div class="text-muted fst-italic mb-2">Posted on {{months}} {{article.created_date.day}}, {{article.created_date.year}} by {{ article.author.username }} ,</div>

                        </header>
                        <!-- Preview image figure-->
                        {% if article.article_img %}
                            <figure class="mb-4"><img style="width:900px;height:400px" class="img-fluid rounded" src="{{article.article_img.url}}" alt="..." /></figure>
                        {% else %}
                            <figure class="mb-4"><img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." /></figure>
                        {% endif %}
                        <!-- Post content-->
                        <section class="mb-5">
                            <p class="fs-5 mb-4">
                                {{article.content | safe}}
                            </p>
                        </section>
                    </article>
                    <!-- Comments section-->
                    <section class="mb-5">
                        <div class="card bg-light">
                            <div class="card-body">
                                <!-- Comment form-->
                                <form class="mb-4" method="post" action="{% url 'article:comment' article.id%}">
                                {% csrf_token %}
                                <input name="comment_content" type="text" class="form-control" rows="3" placeholder="Join the discussion and leave a comment!">
                                <button style="float:right;margin-top:5px;" type="submit" class="btn btn-danger">Add Comment</button>
                                </form>
                                {% if comment %}
                                
                                    {% for comm in comment %}
                                    <div class="d-flex mb-4">
                                    {% if comm.comment_station == '1' %}
                                        <div class="flex-shrink-0"><img style="width:50px;height:50px;" class="rounded-circle" src="{%static 'good.png'%}" alt="..." /></div>
                                    {% endif %}
                                    {% if comm.comment_station == '-1' %}
                                        <div class="flex-shrink-0"><img style="width:50px;height:50px;" class="rounded-circle" src="{%static 'bad.png'%}" alt="..." /></div>
                                    {% endif %}
                                    {% if comm.comment_station == '0' %}
                                        <div class="flex-shrink-0"><img style="width:50px;height:50px;" class="rounded-circle" src="{%static 'normal.png'%}" alt="..." /></div>
                                    {% endif %}
                                        <div class="ms-3">
                                            
                                            <div class="fw-bold">{{comm.comment_author}}</div>
                                            <div style="font-size:12px;">{{comm.comment_date}}</div>
                                            <div class="text-break">{{comm.comment_content}}</div>
                                            
                                        </div>
                                        
                                    </div>
                                    
                                    {% endfor %}
                                        
                                {% else %}
                                <br>
                                    <div class="alert alert-danger">Herhangi bir yorum yapilmamis.</div>
                                {% endif %}
                            </div>
                        </div>
                    </section>
                    
                </div>
</div>


{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}
    <div  class = "mt-5 p-5 bg-danger bg-gradient text-white rounded text-center" >
        <h2 style="color:black" class="fs-2 fw-bold fst-italic">Sabri Alperen Kaya Blogu'na Hosgeldiniz</h3>
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt hic inventore cumque quisquam deleniti architecto deserunt sint error? Veritatis, dolores totam. Quam dolores impedit maxime voluptate? Fugiat velit beatae ipsam.</p>
    </div>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SAK Blog</title>
    <style>
        
    </style>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/myown.css' %}">
    
</head>
<body>

    <div class = "wrapper">
        <div class="header">
            {% include "includes/navbar.html" %}
        </div>
        <div class="main container">
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == "info" %}
                        <div class="alert alert-danger"> {{ message }} </div>
                    {% else %}
                        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <div class="container">
                {% block body %}
                
                {% endblock body %}
            </div>
        </div>
        <div class="footer">
            <footer>
                {% include "includes/footer.html" %}
            </footer>
        </div>
    </div>
        

    <script src="{% static 'js/bootstrap.min.js' %}"> </script>
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
    <script>
  document.addEventListener("DOMContentLoaded", function() {
    const navbarToggle = document.getElementById("navbar-toggle");
    const navbarCollapse = document.getElementById("navbarCollapse");

    navbarToggle.addEventListener("click", function() {
      navbarCollapse.classList.toggle("show");
    });

    // Hamburger menüsü açıldığında, diğer içeriklerin arka plana atılması
    navbarToggle.addEventListener("click", function() {
      document.body.classList.toggle("overlay-active");
    });
  });
</script>

    
</body>

</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}
<div class="row">
    <div class="col-6 col-md-4">
        <h3>Giriş Yap</h3>
        <hr>

        <form method="post">
            {% csrf_token %}
            
            {{form | crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Log In</button>
        </form>
    </div>
</div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}

<div class="row">
  <div class="col-6 col-md-4">
    <h3>Kayıt Ol</h3>
    <hr>
    <form method="post">
    <div class="form-group">
        {% csrf_token %} <!--BU COK ONEMLI MAN IN THE MIDDLE ATACKLARINDAN KORUNMAK ICIN EKLENMELI POST REQUES GEREKTIREN YERLERE -->
        {{form|crispy}}
        <br>
        <button type="submit" class="btn btn-danger">Kayıt Ol</button>
    </div>
    </form>

  </div>
</div>


{% endblock body %}

templates/update.html
{% extends "layout.html" %}

{% block body %}

{% load crispy_forms_tags %}
<div class="row">
    <div class="col">
        <h3>Update Article</h3>
        <hr>

        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form | crispy}}
            <br>
            <button type="submit" class="btn btn-danger">Update Article</button>
        </form>
    </div>
</div>

{% endblock body %}